version: '3'
services:
  mailserver:
    image: analogic/poste.io
    container_name: servermail
    restart: always
    network_mode: "host"
    expose:
      - "25"
      - "80"
      - "443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    environment:
      - TZ=madrid/europe
      - h=mail.jorgenie.com
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - DISABLE_CLAMAW=TRUE
    volumes:
      - /mnt/mail:/data
